# Generated by Django 5.1.4 on 2025-01-17 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('idPers', models.AutoField(primary_key=True, serialize=False)),
                ('nomPers', models.CharField(max_length=42)),
                ('prenomPers', models.CharField(max_length=42)),
                ('mailPers', models.EmailField(max_length=42)),
                ('poidsPers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Poney',
            fields=[
                ('idPon', models.AutoField(primary_key=True, serialize=False)),
                ('nomPon', models.CharField(max_length=42)),
                ('poidsMax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('idAdh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='adherent', serialize=False, to='home.personne')),
                ('cotisationPaye', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('idCours', models.AutoField(primary_key=True, serialize=False)),
                ('nbPersMax', models.IntegerField()),
                ('dateCou', models.DateTimeField()),
                ('duree', models.PositiveSmallIntegerField()),
                ('prixCou', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idMon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='home.cours')),
                ('idPon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='home.poney')),
            ],
        ),
        migrations.CreateModel(
            name='Inscrire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paye', models.BooleanField()),
                ('idCours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='home.cours')),
                ('idAdh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='home.adherent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.CheckConstraint(condition=models.Q(('duree__gte', 1), ('duree__lte', 2)), name='check_duree_range'),
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.CheckConstraint(condition=models.Q(('nbPersMax__gte', 1), ('nbPersMax__lte', 10)), name='check_nbPersMax_range'),
        ),
        migrations.AddConstraint(
            model_name='participer',
            constraint=models.UniqueConstraint(fields=('idCours', 'idPon'), name='unique_participation'),
        ),
    ]
