# Generated by Django 5.1.4 on 2025-01-17 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_inscrire_idadh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inscrire',
            constraint=models.UniqueConstraint(fields=('idCours', 'idAdh'), name='unique_inscription'),
        ),
    ]
